import '../models/ngo_model.dart';
import '../models/repair_task_model.dart';
import '../models/resource_model.dart';
import '../utils/constants.dart';

class LocalDataService {
  // ── HARDCODED NGOs ─────────────────────────────────────────────────────────

  static List<NGOModel> get ngos => [
        NGOModel(
          id: 'ngo_001',
          name: 'Goonj Foundation',
          registrationNumber: 'MH/NGO/2005/001',
          contactPerson: 'Anshu Gupta',
          email: 'contact@goonj.org',
          phone: '+91-11-26972351',
          address: 'C-544, Pocket C, Sarita Vihar, New Delhi - 110076',
          latitude: 28.5355,
          longitude: 77.2730,
          acceptedCategories: ['clothes', 'food', 'books', 'furniture', 'electronics'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 1, 1),
        ),
        NGOModel(
          id: 'ngo_002',
          name: 'Pratham Mumbai',
          registrationNumber: 'MH/NGO/1994/002',
          contactPerson: 'Rukmini Banerji',
          email: 'info@pratham.org',
          phone: '+91-22-26570005',
          address: 'Y.B. Chavan Centre, Gen. J. Bhosale Marg, Mumbai - 400021',
          latitude: 18.9322,
          longitude: 72.8264,
          acceptedCategories: ['books', 'electronics', 'stationery', 'toys'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 2, 1),
        ),
        NGOModel(
          id: 'ngo_003',
          name: 'CRY – Child Rights and You',
          registrationNumber: 'MH/NGO/1979/003',
          contactPerson: 'Puja Marwaha',
          email: 'info@cry.org',
          phone: '+91-22-23063647',
          address: '19, Vidyasagar Setu, Mumbai - 400086',
          latitude: 19.0607,
          longitude: 72.8362,
          acceptedCategories: ['clothes', 'toys', 'books', 'stationery'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 3, 1),
        ),
        NGOModel(
          id: 'ngo_004',
          name: 'Asha for Education – Pune',
          registrationNumber: 'MH/NGO/2001/004',
          contactPerson: 'Suresh Patil',
          email: 'pune@ashanet.org',
          phone: '+91-20-25431122',
          address: 'FC Road, Shivajinagar, Pune - 411005',
          latitude: 18.5236,
          longitude: 73.8478,
          acceptedCategories: ['books', 'stationery', 'electronics', 'furniture'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 4, 1),
        ),
        NGOModel(
          id: 'ngo_005',
          name: 'Helpage India – Bengaluru',
          registrationNumber: 'KA/NGO/1978/005',
          contactPerson: 'Mathew Cherian',
          email: 'bangalore@helpageindia.org',
          phone: '+91-80-22867490',
          address: 'No. 32, 2nd Main Road, Sadashivanagar, Bengaluru - 560080',
          latitude: 13.0036,
          longitude: 77.5710,
          acceptedCategories: ['clothes', 'furniture', 'medical', 'food', 'electronics'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 5, 1),
        ),
        NGOModel(
          id: 'ngo_006',
          name: 'Smile Foundation – Chennai',
          registrationNumber: 'TN/NGO/2002/006',
          contactPerson: 'Santanu Mishra',
          email: 'chennai@smilefoundationindia.org',
          phone: '+91-44-24612345',
          address: '14, III Main Road, Kasturba Nagar, Chennai - 600020',
          latitude: 13.0418,
          longitude: 80.2341,
          acceptedCategories: ['clothes', 'food', 'toys', 'books', 'stationery'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 6, 1),
        ),
        NGOModel(
          id: 'ngo_007',
          name: 'Akshaya Patra – Hyderabad',
          registrationNumber: 'TS/NGO/2000/007',
          contactPerson: 'Chanchalapathi Dasa',
          email: 'hyderabad@akshayapatra.org',
          phone: '+91-40-23547890',
          address: 'Plot No. 4, Necklace Road, Hyderabad - 500082',
          latitude: 17.4065,
          longitude: 78.4772,
          acceptedCategories: ['food', 'clothes', 'stationery'],
          isActive: true,
          isVerified: true,
          createdAt: DateTime(2023, 7, 1),
        ),
      ];

  // ── HARDCODED REPAIR TASKS (Helpers) ──────────────────────────────────────

  static List<RepairTaskModel> get repairTasks => [
        RepairTaskModel(
          id: 'task_001',
          itemId: 'item_demo_001',
          contributorId: 'user_demo',
          repairType: 'Electronics',
          description:
              'Old laptop (Dell Inspiron) — screen flickering, keyboard keys stuck. Needs display cable check and keyboard replacement.',
          status: AppConstants.statusPending,
          estimatedCost: '800',
          createdAt: DateTime.now().subtract(const Duration(hours: 3)),
        ),
        RepairTaskModel(
          id: 'task_002',
          itemId: 'item_demo_002',
          contributorId: 'user_demo',
          repairType: 'Furniture',
          description:
              'Wooden chair — two legs cracked, seat cushion torn. Basic carpentry and re-upholstery needed.',
          status: AppConstants.statusPending,
          estimatedCost: '350',
          createdAt: DateTime.now().subtract(const Duration(hours: 6)),
        ),
        RepairTaskModel(
          id: 'task_003',
          itemId: 'item_demo_003',
          contributorId: 'user_demo',
          repairType: 'Electronics',
          description:
              'Android tablet — cracked screen, battery drains fast. Screen replacement + battery swap required.',
          status: AppConstants.statusPending,
          estimatedCost: '1200',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        RepairTaskModel(
          id: 'task_004',
          itemId: 'item_demo_004',
          contributorId: 'user_demo',
          repairType: 'Clothing',
          description:
              'Bag of children\'s clothes — torn seams, missing buttons. Tailoring work for 12–15 garments.',
          status: AppConstants.statusPending,
          estimatedCost: '200',
          createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
        ),
        RepairTaskModel(
          id: 'task_005',
          itemId: 'item_demo_005',
          contributorId: 'user_demo',
          repairType: 'Appliance',
          description:
              'Table fan — motor humming but blade not spinning. Capacitor likely blown, needs replacement.',
          status: AppConstants.statusPending,
          estimatedCost: '450',
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
        RepairTaskModel(
          id: 'task_006',
          itemId: 'item_demo_006',
          contributorId: 'user_demo',
          repairType: 'Footwear',
          description:
              '3 pairs of school shoes — sole detached, one pair needs stitching. Cobbler work.',
          status: AppConstants.statusPending,
          estimatedCost: '150',
          createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 8)),
        ),
      ];

  // ── HARDCODED DONATION ITEMS (for NGO dashboard) ──────────────────────────

  static List<ResourceModel> get availableItems => [
        ResourceModel(
          id: 'item_001',
          userId: 'user_demo_1',
          imageUrl: '',
          description: 'Set of 25 story books for children aged 6–12, good condition.',
          itemName: 'Children\'s Story Books',
          category: 'books',
          condition: 'good',
          aiClassification: AppConstants.classUsable,
          location: 'Bandra, Mumbai',
          latitude: 19.0544,
          longitude: 72.8405,
          status: AppConstants.statusClassified,
          createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        ),
        ResourceModel(
          id: 'item_002',
          userId: 'user_demo_2',
          imageUrl: '',
          description:
              'Winter clothes bundle — 8 sweaters, 4 jackets, good condition, sizes S to L.',
          itemName: 'Winter Clothes Bundle',
          category: 'clothes',
          condition: 'good',
          aiClassification: AppConstants.classUsable,
          location: 'Koregaon Park, Pune',
          latitude: 18.5362,
          longitude: 73.8956,
          status: AppConstants.statusClassified,
          createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        ),
        ResourceModel(
          id: 'item_003',
          userId: 'user_demo_3',
          imageUrl: '',
          description:
              'School stationery pack — notebooks, pencils, erasers, rulers for ~20 students.',
          itemName: 'School Stationery Pack',
          category: 'stationery',
          condition: 'new',
          aiClassification: AppConstants.classUsable,
          location: 'Indiranagar, Bengaluru',
          latitude: 12.9784,
          longitude: 77.6408,
          status: AppConstants.statusClassified,
          createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        ),
        ResourceModel(
          id: 'item_004',
          userId: 'user_demo_4',
          imageUrl: '',
          description:
              'Wooden study table with chair, minor scratches, fully functional.',
          itemName: 'Study Table + Chair',
          category: 'furniture',
          condition: 'good',
          aiClassification: AppConstants.classUsable,
          location: 'Adyar, Chennai',
          latitude: 13.0050,
          longitude: 80.2563,
          status: AppConstants.statusClassified,
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        ResourceModel(
          id: 'item_005',
          userId: 'user_demo_5',
          imageUrl: '',
          description:
              'Box of assorted toys — dolls, building blocks, puzzles. Clean and safe.',
          itemName: 'Assorted Toy Box',
          category: 'toys',
          condition: 'good',
          aiClassification: AppConstants.classUsable,
          location: 'Banjara Hills, Hyderabad',
          latitude: 17.4156,
          longitude: 78.4347,
          status: AppConstants.statusClassified,
          createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
        ),
        ResourceModel(
          id: 'item_006',
          userId: 'user_demo_6',
          imageUrl: '',
          description:
              'Android smartphone (Redmi Note 8), screen cracked but working fine.',
          itemName: 'Redmi Note 8 Smartphone',
          category: 'electronics',
          condition: 'needs_repair',
          aiClassification: AppConstants.classRepairable,
          repairType: 'screen',
          repairDescription: 'Screen cracked, display still functional.',
          location: 'Karol Bagh, New Delhi',
          latitude: 28.6519,
          longitude: 77.1909,
          status: AppConstants.statusClassified,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
      ];
}
