// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAePQpx0JguI1den3gK7nCkOI4Wu63ucP0',
    appId: '1:935019926172:web:8b1bab69f48799e0ea5359',
    messagingSenderId: '935019926172',
    projectId: 'resource-bridge-5eb83',
    authDomain: 'resource-bridge-5eb83.firebaseapp.com',
    databaseURL: 'https://resource-bridge-5eb83-default-rtdb.firebaseio.com',
    storageBucket: 'resource-bridge-5eb83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOK_msKZQ7Lqg1yzvqVETSi5hKZSQTeo',
    appId: '1:935019926172:android:75b542689b56551aea5359',
    messagingSenderId: '935019926172',
    projectId: 'resource-bridge-5eb83',
    databaseURL: 'https://resource-bridge-5eb83-default-rtdb.firebaseio.com',
    storageBucket: 'resource-bridge-5eb83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlK0RagFB97c1eM9URAbroPWwTTvdFfUA',
    appId: '1:935019926172:ios:6006a38f5c70fa93ea5359',
    messagingSenderId: '935019926172',
    projectId: 'resource-bridge-5eb83',
    databaseURL: 'https://resource-bridge-5eb83-default-rtdb.firebaseio.com',
    storageBucket: 'resource-bridge-5eb83.firebasestorage.app',
    iosBundleId: 'com.example.resourceBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlK0RagFB97c1eM9URAbroPWwTTvdFfUA',
    appId: '1:935019926172:ios:6006a38f5c70fa93ea5359',
    messagingSenderId: '935019926172',
    projectId: 'resource-bridge-5eb83',
    databaseURL: 'https://resource-bridge-5eb83-default-rtdb.firebaseio.com',
    storageBucket: 'resource-bridge-5eb83.firebasestorage.app',
    iosBundleId: 'com.example.resourceBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAePQpx0JguI1den3gK7nCkOI4Wu63ucP0',
    appId: '1:935019926172:web:7873fb4551a6be12ea5359',
    messagingSenderId: '935019926172',
    projectId: 'resource-bridge-5eb83',
    authDomain: 'resource-bridge-5eb83.firebaseapp.com',
    databaseURL: 'https://resource-bridge-5eb83-default-rtdb.firebaseio.com',
    storageBucket: 'resource-bridge-5eb83.firebasestorage.app',
  );
}